"""Publish owned wiki pages while preserving hand-written pages and Git history."""
import argparse
import os
from pathlib import Path
import re
import subprocess
import tempfile

MARKER = "<!-- Generated by Marketing Brain knowledge action. -->"
SIDEBAR_START = "<!-- marketing-brain-navigation:start -->"
SIDEBAR_END = "<!-- marketing-brain-navigation:end -->"


def sync_pages(source, target):
    pages = {}
    for path in source.iterdir():
        if path.is_symlink() or not path.is_file() or not path.name.startswith("Brain-") or path.suffix != ".md":
            raise ValueError("Unexpected wiki input file")
        content = path.read_text()
        if not content.startswith(MARKER):
            raise ValueError("Wiki input is missing its ownership marker")
        pages[path.name] = content
    if "Brain-Home.md" not in pages:
        raise ValueError("No generated wiki home page")

    # Validate every destination before deleting stale pages or writing any updates.
    owned = set()
    for path in target.glob("Brain-*.md"):
        if path.is_symlink():
            raise ValueError("Wiki destination contains a symlink")
        if path.read_text().startswith(MARKER):
            owned.add(path.name)
        elif path.name in pages:
            raise ValueError(f"Refusing to overwrite a hand-written wiki page: {path.name}")
    sidebar = target / "_Sidebar.md"
    if sidebar.is_symlink():
        raise ValueError("Wiki sidebar is a symlink")
    text = sidebar.read_text() if sidebar.exists() else ""
    if text.count(SIDEBAR_START) != text.count(SIDEBAR_END) or text.count(SIDEBAR_START) > 1:
        raise ValueError("Malformed managed wiki navigation block")
    block = f"{SIDEBAR_START}\n- [Marketing Brain](Brain-Home)\n{SIDEBAR_END}"
    if SIDEBAR_START in text:
        start, end = text.index(SIDEBAR_START), text.index(SIDEBAR_END)
        if end < start:
            raise ValueError("Malformed managed wiki navigation block")
        text = text[:start] + block + text[end + len(SIDEBAR_END):]
    else:
        text = text.rstrip() + ("\n\n" if text.strip() else "") + block + "\n"
    for name in owned - pages.keys():
        (target / name).unlink()
    for name, content in pages.items():
        (target / name).write_text(content)
    sidebar.write_text(text)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, required=True)
    args = parser.parse_args()
    repository = os.environ.get("GITHUB_REPOSITORY", "")
    revision = os.environ.get("GITHUB_SHA", "")
    if not re.fullmatch(r"[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+", repository) or not re.fullmatch(r"[a-f0-9]{40}", revision):
        raise ValueError("Expected a GitHub repository and full source commit SHA")
    if not os.environ.get("WIKI_TOKEN"):
        raise ValueError("Set the WIKI_TOKEN Actions secret before publishing")
    env = dict(os.environ, GIT_TERMINAL_PROMPT="0")
    # The helper expands the secret in its environment, never into a URL or argv.
    helper = '!f() { printf "%s\\n" "username=x-access-token" "password=$WIKI_TOKEN"; }; f'
    command = ["git", "-c", "credential.helper=", "-c", "credential.helper=" + helper]
    remote = f"https://github.com/{repository}"
    head = subprocess.check_output(command + ["ls-remote", remote + ".git", "refs/heads/main"], env=env).decode().split()
    if not head or head[0] != revision:
        print("Wiki not published: this build is no longer the current main revision.")
        return
    with tempfile.TemporaryDirectory(prefix="brain-wiki-") as directory:
        target = Path(directory) / "wiki"
        subprocess.run(command + ["clone", "--depth=1", remote + ".wiki.git", str(target)], check=True, env=env)
        sync_pages(args.source, target)
        subprocess.run(["git", "-C", str(target), "add", "--", "Brain-*.md", "_Sidebar.md"], check=True)
        diff = subprocess.run(["git", "-C", str(target), "diff", "--cached", "--quiet"])
        if diff.returncode == 0:
            print("Wiki already up to date.")
            return
        if diff.returncode != 1:
            raise RuntimeError("Could not compare wiki changes")
        subprocess.run(["git", "-C", str(target), "-c", "user.name=github-actions[bot]", "-c", "user.email=41898282+github-actions[bot]@users.noreply.github.com", "commit", "-m", f"Refresh Marketing Brain knowledge from {revision[:12]}"], check=True)
        subprocess.run(command + ["-C", str(target), "push", "origin", "HEAD"], check=True, env=env)
        print(f"Published wiki for {revision}.")


if __name__ == "__main__":
    main()
